services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - myapp-network

  web:
    build: .
    command: bash -c "
      for i in {1..10}; do
        pg_isready -h db -U postgres && break;
        echo 'Waiting for database...';
        sleep 5;
      done &&
      bin/rails db:create db:schema:load &&
      rails test"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_test
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    networks:
      - myapp-network

networks:
  myapp-network:
