default: &default
  adapter: postgresql
  encoding: unicode
  host: db     # Set host to the name of the PostgreSQL service in docker-compose.yml
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development
  username: postgres
  password: password

test:
  <<: *default
  database: myapp_test
  username: postgres
  password: password

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
