name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.9

      - name: Install dependencies
        run: |
          gem install bundler -v 2.2.33
          bundle install --jobs 4 --retry 3

      - name: Set execute permissions for Rails
        run: chmod +x bin/rails

      - name: Set up database
        run: |
          for i in {1..5}; do
            bin/rails db:create db:schema:load && break || sleep 5
          done

      - name: Run tests
        run: |
          bin/rails test
